name: nb-lewagon-py38
dependencies:
  - python=3.8
  - pip
  - pip:
    - dtale
    - ipywidgets
    - matplotlib
    - nbgitpuller
    - numpy
    - Pillow
    - plotly
    - pandas-profiling
    - seaborn
    - statsmodels
    - tensorflow
    - xgboost
